# Generated by Django 6.0.2 on 2026-02-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=120)),
                ('room', models.CharField(max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('available_seats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shows', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='catalog.shows')),
            ],
        ),
    ]
