# Generated by Django 6.0.2 on 2026-02-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='nombre',
        ),
        migrations.AddField(
            model_name='shows',
            name='available_seats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shows',
            name='movie_title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='shows',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='room',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('seats', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('Cancelado', 'cancelado')], default='reservado', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='catalog.shows')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
